name: pahala
description: Personal Augmented Health and Lifestyle Assistant.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.5.0
  shared_preferences: ^0.4.3
  flutter_sparkline: ^0.1.0
  month_picker_strip: ^0.0.3
  animated_background: ^1.0.0
  flutter_spinkit: ^3.0.0
  card_settings: ^1.2.1
  intro_views_flutter: ^2.4.0
  flushbar: ^1.1.2
  animated_text_kit: ^1.1.1
  font_awesome_flutter: ^8.2.0
  flutter_swiper: ^1.1.4
  oauth2: ^1.2.3
  http: ^0.11.3
  json_serializable: ^1.5.1
  url_launcher: ^4.0.1
  flutter_launcher_icons: ^0.6.1
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  geolocator: ^2.1.0
  flutter_blue: ^0.4.1
  timeline: ^0.0.1
  datetime_picker_formfield: ^0.1.7
  time_machine: ^0.9.6
  date_format: ^1.0.5
  numberpicker: ^0.1.7
  material_switch: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFE1F2ED"
  adaptive_icon_foreground: "assets/images/icon-fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/sky/
    - assets/images/weather/
    - assets/images/vendor/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
      - family: Proxima Nova
        fonts:
          - asset: assets/fonts/default/Proxima_Nova_Thin.otf
            weight: 200
          - asset: assets/fonts/default/Proxima_Nova_Thin_Italic.otf
            weight: 200
            style: italic
          - asset: assets/fonts/default/Proxima_Nova_Light.otf
            weight: 300
          - asset: assets/fonts/default/Proxima_Nova_Light.otf
            weight: 300
            style: italic
          - asset: assets/fonts/default/Proxima_Nova_Regular.otf
          - asset: assets/fonts/default/Proxima_Nova_Regular_Italic.otf
            style: italic
          - asset: assets/fonts/default/Proxima_Nova_Semibold.otf
            weight: 600
          - asset: assets/fonts/default/Proxima_Nova_Semibold_Italic.otf
            weight: 600
            style: italic
          - asset: assets/fonts/default/Proxima_Nova_Bold.otf
            weight: 700
          - asset: assets/fonts/default/Proxima_Nova_Bold_Italic.otf
            weight: 700
            style: italic
          - asset: assets/fonts/default/Proxima_Nova_Extrabold.otf
            weight: 800
          - asset: assets/fonts/default/Proxima_Nova_Extrabold_Italic.otf
            weight: 800
            style: italic
          - asset: assets/fonts/default/Proxima_Nova_Black.otf
            weight: 900
          - asset: assets/fonts/default/Proxima_Nova_Black_Italic.otf
            weight: 900
            style: italic